collections:
  team:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: []

plugins:
  - jekyll-octicons

sass:
  load_paths:
    - _sass
    - node_modules
