collections:
  team:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

exclude: []

sass:
  load_paths:
    - _sass
    - node_modules
