version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    working_directory: ~/komolion.github.io
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm install
            bundle install
            bundle exec jekyll build
      - run:
          name: Deploy project
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/deploy.sh
            fi
