version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    working_directory: ~/komolionfund.org
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm install
            bundle install
            bundle exec jekyll build
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/komolionfund.org
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync jekyll/_site/ s3://komolionfund.org/ --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
