version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    working_directory: ~/komolion.github.io
    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          bundle install
          npm install
      - run:
        name: build project
        command: |
          bundle exec jekyll build
