version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    working_directory: ~/komolion.github.io
    steps:
      - checkout
      - run:
          name: install
          command: |
            bundle install
            npm install
      - run:
          name: build
          command: |
            bundle exec jekyll build
      - run:
          name: deploy
          command: |
            if [ $CIRCLE_BRANCH == $DEPLOY_BRANCH ]; then
              bash .circleci/deploy.sh
            fi
