version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    working_directory: ~/deployment
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm install
            bundle install
            bundle exec jekyll build
      - persist_to_workspace:
          root: .
          paths: _site/
  deploy:
    docker:
      - image: circleci/python
    working_directory: ~/deployment
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - attach_workspace:
          at: ~/deployment
      - run:
          name: Deploy to S3
          command: aws s3 sync ./_site/ s3://komolionfund.org/ —delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
