version: 2
jobs:
  build:

    # Docker image
    docker:
      - image: circleci/ruby:2.5-node-browsers

    # Working directory
    working_directory: ~/komolion.github.io

    # Ignore master
    branches:
      ignore:
        - master

    # Deployment steps
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            npm install
            bundle install
            bundle exec jekyll build
      - run:
          name: Deploy project
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/deploy.sh
            fi
